#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=bottom \
  height=30 \
  y_offset=5 \
  blur_radius=30 \
  color=0x44000000 \
  margin=10 \
  corner_radius=100 \
  padding_left=10 \
  padding_right=10 \
  topmost=window

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Bold:12.0"
  label.font="SF Pro:Bold:12.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=8
  icon.padding_right=8
  label.padding_left=0
  label.padding_right=8
  background.color=0x00000000
  background.corner_radius=5
  background.height=25
)
sketchybar --default "${default[@]}"

sketchybar -m --add item apple_logo left \
  --set apple_logo icon="􀣺" \
  --set apple_logo label.drawing=off


source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/media.sh
# source $ITEM_DIR/spotify.sh
source $ITEM_DIR/window_title.sh



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
